# Generated by Django 4.2.7 on 2024-01-18 07:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(limit_value=50), django.core.validators.RegexValidator(message='Only alphabets are allowed.', regex='^[A-Za-z]*$')])),
                ('middle_name', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(limit_value=50), django.core.validators.RegexValidator(message='Only alphabets are allowed.', regex='^[A-Za-z]*$')])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(limit_value=50), django.core.validators.RegexValidator(message='Only alphabets are allowed.', regex='^[A-Za-z]*$')])),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], max_length=1)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('mobile', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Mobile number must be 10 digits long.', regex='^[0-9]{10}$')])),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(limit_value=8), django.core.validators.MaxLengthValidator(limit_value=20)])),
                ('newsletter', models.BooleanField(default=False)),
            ],
        ),
    ]
