# Generated by Django 4.2.7 on 2024-01-18 07:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=50, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Only alphabets are allowed.', regex='^[A-Za-z]*$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Only alphabets are allowed.', regex='^[A-Za-z]*$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='middle_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Only alphabets are allowed.', regex='^[A-Za-z]*$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Password must be 8 to 20 characters long and contain at least 1 number and 1 symbol.', regex='^(?=.*[0-9])(?=.*[!@#$%^&*()_+{}|:"<>?`\\-=[\\];\',./]).{8,20}$')]),
        ),
    ]
