# Generated by Django 4.2.7 on 2024-01-18 07:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0002_alter_userprofile_email_alter_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Password must be 8 to 20 characters long and contain at least 1 number and 1 symbol.', regex='^(?=.*[0-9])(?=.*[!@#$%^&*()_+{}|:"<>?`-=[\\];\',./]).{8,20}$')]),
        ),
    ]
