# Generated by Django 4.2.7 on 2024-01-19 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0004_alter_userprofile_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
